# -*- coding: utf-8 -*-
"""NBA Data Collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7Jt65E3K8J4SP2Icj80V0BOm6f2tblx

# Data Collection and Formatting
This file will use python to webscrape and wrangle data from Basketball Reference. This is the first step of my project to analyze basketball players' playstyles. I will be collecting all sorts of data on the players, including common statistics and advanced metrics.
"""

import pandas as pd
import re
import numpy as np
from functools import reduce

"""## Web Scraping

### Per Game Stats
"""

# assign the webpage url to an object
url1 = "https://www.basketball-reference.com/leagues/NBA_2024_per_game.html"

# read in the html using pandas
PerGame24 = pd.read_html(url1)

# see how many tables are in the html
len(PerGame24)

# select the first (and only) table
pg24 = PerGame24[0]

# look at the first ten rows of the table
pg24.head(10)

# remove duplicates for players. keep first instance which represents player's overall season
pg24.drop_duplicates(subset = ['Player'], keep = 'first', inplace = True)

# Drop unwanted variables
pg24.drop(['Rk'], axis = 1, inplace = True)

# rename columns by referring to the old column name
pg24.rename(columns = {'FG':'FGM', '3P':'3PM', '2P':'2PM', 'FT':'FTM'}, inplace = True)

# check structure of dataset
pg24.info()

"""### Offensive and Defensive Rating"""

url2 = "https://www.basketball-reference.com/leagues/NBA_2024_per_poss.html"

PerPoss24 = pd.read_html(url2)

len(PerPoss24)

pp24 = PerPoss24[0]
pp24.drop_duplicates(subset = ['Player'], keep = 'first', inplace = True)
# keep only the offensive and defensive rating stats from this dataset
pp24 = pp24[['Player','ORtg','DRtg']]
pp24.head(10)

pp24.info()

"""### Advanced Stats"""

url3 = "https://www.basketball-reference.com/leagues/NBA_2024_advanced.html"
Adv24 = pd.read_html(url3)
len(Adv24)

adv24 = Adv24[0]
adv24.drop_duplicates(subset = ['Player'], keep = 'first', inplace = True)
adv24.drop(['Rk', 'Pos', 'Age', 'Tm', 'G', 'MP', 'Unnamed: 19', 'Unnamed: 24'], axis = 1, inplace = True)
adv24.head(10)

adv24.info()

"""### Play-by-Play Stats"""

url4 = "https://www.basketball-reference.com/leagues/NBA_2024_play-by-play.html"
Play24 = pd.read_html(url4)
len(Play24)
pbp24 = Play24[0]
pbp24.info()

# the column headers in this dataset are multilevel. keep only the first level
pbp24.columns = pbp24.columns.get_level_values(1)

# Generate unique column names if duplicates are found
def make_unique(columns):
    seen = set()
    new_columns = []
    for col in columns:
        new_col = col
        while new_col in seen:
            new_col = f"{col}_dup"
        seen.add(new_col)
        new_columns.append(new_col)
    return new_columns

# Apply unique names
pbp24.columns = make_unique(pbp24.columns)

# rename columns by column index number
pbp24.rename(columns={pbp24.columns[16]: 'SFC',
                      pbp24.columns[17]: 'OFC',
                      pbp24.columns[18]: 'SFD',
                      pbp24.columns[19]: 'OFD'},
             inplace=True)

# drop duplicate rows
pbp24.drop_duplicates(subset = ['Player'], keep = 'first', inplace = True)

# drop unwanted variables
pbp24.drop(['Rk', 'Pos', 'Age', 'Tm', 'G', 'MP'], axis = 1, inplace = True)

pbp24.info()

pbp24.info()

# replace the NaN occurrences with 0
pbp24.fillna(0, inplace = True)
pbp24.head(10)

"""### Shooting Stats"""

url5 = "https://www.basketball-reference.com/leagues/NBA_2024_shooting.html"
Shoot24 = pd.read_html(url5)
len(Shoot24)

sho24 = Shoot24[0]
sho24.columns = sho24.columns.get_level_values(1)
sho24.drop_duplicates(subset = ['Player'], keep = 'first', inplace = True)
sho24.drop(sho24.columns[sho24.columns.str.contains('Unnamed',case = False)],axis = 1, inplace = True)
sho24.drop(['Rk', 'Pos', 'Age', 'Tm', 'G', 'MP', 'FG%'], axis = 1, inplace = True)
sho24.info()

sho24.columns.values[1]= 'Dist'
sho24.columns.values[2]= '%2P'
sho24.columns.values[3]= '%0-3'
sho24.columns.values[4]= '%3-10'
sho24.columns.values[5]= '%10-16'
sho24.columns.values[6]= '%16-3P'
sho24.columns.values[7]= '%3P'
sho24.columns.values[8]= '2P%'
sho24.columns.values[9]= '0-3%'
sho24.columns.values[10]= '3-10%'
sho24.columns.values[11]= '10-16%'
sho24.columns.values[12]= '16-3P%'
sho24.columns.values[13]= '3P%'
sho24.columns.values[14]= '%2PA'
sho24.columns.values[15]= '%3PA'
sho24.columns.values[16]= '%FGAD'
sho24.columns.values[17]= '#D'
sho24.columns.values[18]= '%C3PA'
sho24.columns.values[19]= 'C3P%'


#Drop unwanted variables
sho24.drop(['2P%', '3P%', 'Att.', '#'], axis = 1, inplace = True)

sho24.info()

"""## Merge Web Scraped Data"""

# Merging the DataFrames together
## List the datasets to merge
dfs = [pg24, pp24, adv24, pbp24, sho24]

## Merge the datasets
web_df = reduce(lambda left, right: pd.merge(left, right, on='Player'), dfs)

## Fix Player Names
web_df['Player'] = web_df['Player'].str.replace('.', '', regex=False)

## Check the first few rows
web_df.head()

web_df.info()

"""Now, we can clean this dataframe before moving forward."""

# Drop unwanted columns
web_df.drop(['PG%', 'SG%', 'SF%', 'PF%', 'C%'], axis=1, inplace=True)

# Replace NaNs with 0
web_df.fillna(0, inplace=True)

"""## Using nba_api"""

!pip install nba-api --upgrade

from nba_api.stats.endpoints import commonallplayers
from nba_api.stats.library.parameters import SeasonTypeAllStar

# Example using generic endpoint
from nba_api.stats.endpoints import LeagueHustleStatsPlayer

"""### Hustle Stats"""

# Get hustle stats for the 2023-24 season
hustle_stats = LeagueHustleStatsPlayer(season='2023-24', per_mode_time = 'PerGame', season_type_all_star = 'Regular Season')

# Convert to DataFrame
hustle_stats_df = hustle_stats.get_data_frames()[0]

# Display first few rows
hustle_stats_df.head()

# Drop unwanted variables
hustle_stats_df.drop(['PLAYER_ID', 'TEAM_ID', 'AGE', 'MIN'], axis = 1, inplace = True)

# Get structure of dataset
hustle_stats_df.info()

"""### Passing Stats"""

from nba_api.stats.endpoints import LeagueDashPtStats

# Fetch passing tracking stats for the 2023-24 season
passing_stats = LeagueDashPtStats(season='2023-24', season_type_all_star='Regular Season', player_or_team = 'Player', per_mode_simple='PerGame', pt_measure_type = 'Passing')

# Convert to a DataFrame
passing_stats_df = passing_stats.get_data_frames()[0]

# Display the first few rows
passing_stats_df.info()

# Drop unwanted variables
passing_stats_df.drop(['PLAYER_ID', 'TEAM_ID', 'W', 'L', 'MIN'], axis = 1, inplace = True)

# rename column
passing_stats_df.rename(columns = {'GP' : 'G'}, inplace = True)

"""### Rebounding Stats"""

# Fetch rebounding tracking stats for the 2023-24 season
reb_stats = LeagueDashPtStats(season='2023-24', season_type_all_star='Regular Season', player_or_team = 'Player', per_mode_simple='PerGame', pt_measure_type = 'Rebounding')

# Convert to a DataFrame
reb_stats_df = reb_stats.get_data_frames()[0]

# Display the structure
reb_stats_df.info()

# Keep desired columns (variables)
reb_stats_df = reb_stats_df[['PLAYER_NAME', 'TEAM_ABBREVIATION', 'GP', 'OREB_CHANCES', 'DREB_CHANCES', 'REB_CHANCES', 'REB_CHANCE_PCT']]

# Rename column
reb_stats_df.rename(columns = {'GP' : 'G'}, inplace = True)

# View the dataset
reb_stats_df.head()

"""### Post Up Stats"""

# Fetch Post Up tracking stats for the 2023-24 season
post_stats = LeagueDashPtStats(season='2023-24', season_type_all_star='Regular Season', player_or_team = 'Player', per_mode_simple='PerGame', pt_measure_type = 'PostTouch')

# Convert to a DataFrame
post_stats_df = post_stats.get_data_frames()[0]

# Display the structure
post_stats_df.info()

# Keep desired columns (variables)
post_stats_df = post_stats_df[['PLAYER_NAME', 'TEAM_ABBREVIATION', 'GP', 'POST_TOUCHES', 'POST_TOUCH_PTS']]

# Rename column
post_stats_df.rename(columns = {'GP' : 'G'}, inplace = True)

# View the dataset
post_stats_df.sort_values(by = 'POST_TOUCHES', ascending = False)

"""### Isolation Stats"""

from nba_api.stats.endpoints import SynergyPlayTypes

# Fetch Isolation play type stats for the 2023-24 season
iso_stats = SynergyPlayTypes(season='2023-24', season_type_all_star='Regular Season', player_or_team_abbreviation = 'P', per_mode_simple='PerGame', play_type_nullable = 'Isolation', type_grouping_nullable = 'Offensive')

# Convert to a DataFrame
iso_stats_df = iso_stats.get_data_frames()[0]

# Display the structure
iso_stats_df.info()

iso_stats_df.head()

# Keep desired columns (variables)
iso_stats_df = iso_stats_df[['PLAYER_NAME', 'TEAM_ABBREVIATION', 'GP', 'PTS', 'POSS_PCT', 'PPP', 'POSS']]

# Change column names
# Identify columns 4 to 7 (indexing starts at 0)
cols_to_modify = iso_stats_df.columns[3:7]

# Prepend 'ISO_' to these column names
iso_stats_df.columns = [f'ISO_{col}' if col in cols_to_modify else col for col in iso_stats_df.columns]

# rename column
iso_stats_df.rename(columns = {'GP' : 'G'}, inplace = True)

# View the dataset
iso_stats_df.head()

"""### PnR Ball Handler Stats"""

# Fetch PnR Ball Handler play type stats for the 2023-24 season
pnr_ball = SynergyPlayTypes(season='2023-24', season_type_all_star='Regular Season', player_or_team_abbreviation = 'P', per_mode_simple='PerGame', play_type_nullable = 'PRBallHandler', type_grouping_nullable = 'Offensive')

# Convert to a DataFrame
pnr_ball_df = pnr_ball.get_data_frames()[0]

# Display the structure
pnr_ball_df.info()

# Keep desired columns (variables)
pnr_ball_df = pnr_ball_df[['PLAYER_NAME', 'TEAM_ABBREVIATION', 'GP', 'PTS', 'POSS_PCT', 'PPP', 'POSS']]

# Change column names
# Identify columns 4 to 7 (indexing starts at 0)
cols_to_modify = pnr_ball_df.columns[3:7]

# Prepend 'PRB_' to these column names
pnr_ball_df.columns = [f'PRB_{col}' if col in cols_to_modify else col for col in pnr_ball_df.columns]

# rename column
pnr_ball_df.rename(columns = {'GP' : 'G'}, inplace = True)

# View the dataset
pnr_ball_df.head()

"""### PnR Roller Stats"""

# Fetch PnR Ball Handler play type stats for the 2023-24 season
pnr_roll = SynergyPlayTypes(season='2023-24', season_type_all_star='Regular Season', player_or_team_abbreviation = 'P', per_mode_simple='PerGame', play_type_nullable = 'PRRollman', type_grouping_nullable = 'Offensive')

# Convert to a DataFrame
pnr_roll_df = pnr_roll.get_data_frames()[0]

# Display the structure
pnr_roll_df.info()

# Keep desired columns (variables)
pnr_roll_df = pnr_roll_df[['PLAYER_NAME', 'TEAM_ABBREVIATION', 'GP', 'PTS', 'POSS_PCT', 'PPP', 'POSS']]

# Change column names
# Identify columns 4 to 7 (indexing starts at 0)
cols_to_modify = pnr_roll_df.columns[3:7]

# Prepend 'PRR_' to these column names
pnr_roll_df.columns = [f'PRR_{col}' if col in cols_to_modify else col for col in pnr_roll_df.columns]

# rename column
pnr_roll_df.rename(columns = {'GP' : 'G'}, inplace = True)

# View the dataset
pnr_roll_df.head()

"""### Spot Up Stats"""

# Fetch Spot Up play type stats for the 2023-24 season
spot_up = SynergyPlayTypes(season='2023-24', season_type_all_star='Regular Season', player_or_team_abbreviation = 'P', per_mode_simple='PerGame', play_type_nullable = 'Spotup', type_grouping_nullable = 'Offensive')

# Convert to a DataFrame
spot_up_df = spot_up.get_data_frames()[0]

# Display the structure
spot_up_df.info()

# Keep desired columns (variables)
spot_up_df = spot_up_df[['PLAYER_NAME', 'TEAM_ABBREVIATION', 'GP', 'PTS', 'POSS_PCT', 'PPP', 'POSS']]

# Change column names
# Identify columns 4 to 7 (indexing starts at 0)
cols_to_modify = spot_up_df.columns[3:7]

# Prepend 'SU_' to these column names
spot_up_df.columns = [f'SU_{col}' if col in cols_to_modify else col for col in spot_up_df.columns]

# rename column
spot_up_df.rename(columns = {'GP' : 'G'}, inplace = True)

# View the dataset
spot_up_df.head()

"""### Cutting Stats"""

# Fetch Cutting play type stats for the 2023-24 season
cut_stats = SynergyPlayTypes(season='2023-24', season_type_all_star='Regular Season', player_or_team_abbreviation = 'P', per_mode_simple='PerGame', play_type_nullable = 'Cut', type_grouping_nullable = 'Offensive')

# Convert to a DataFrame
cut_stats_df = cut_stats.get_data_frames()[0]

# Display the structure
cut_stats_df.info()

# Keep desired columns (variables)
cut_stats_df = cut_stats_df[['PLAYER_NAME', 'TEAM_ABBREVIATION', 'GP', 'PTS', 'POSS_PCT', 'PPP', 'POSS']]

# Change column names
# Identify columns 4 to 7 (indexing starts at 0)
cols_to_modify = cut_stats_df.columns[3:7]

# Prepend 'CUT_' to these column names
cut_stats_df.columns = [f'CUT_{col}' if col in cols_to_modify else col for col in cut_stats_df.columns]

# rename column
cut_stats_df.rename(columns = {'GP' : 'G'}, inplace = True)

# View the dataset
cut_stats_df.head()

"""### Defensive Stats"""

from nba_api.stats.endpoints import LeagueDashPtDefend

# Get defensive stats from 2023-2024 season
def_stats = LeagueDashPtDefend(season = '2023-24', season_type_all_star = 'Regular Season', per_mode_simple = 'PerGame', defense_category = 'Overall')

# Convert to a DataFrame
def_stats_df = def_stats.get_data_frames()[0]

# Display the structure
def_stats_df.head()

# Keep desired columns (variables)
def_stats_df = def_stats_df[['PLAYER_NAME', 'PLAYER_LAST_TEAM_ABBREVIATION', 'GP', 'D_FGA', 'D_FG_PCT', 'PCT_PLUSMINUS']]

# rename column
def_stats_df.rename(columns = {'PLAYER_LAST_TEAM_ABBREVIATION' : 'TEAM_ABBREVIATION', 'GP' : 'G'}, inplace = True)

# View the dataset
def_stats_df.head()

"""### Other Advanced Stats"""

from nba_api.stats.endpoints import LeagueDashPlayerStats

# Get advanced stats from 2023-2024 season
adv_stats = LeagueDashPlayerStats(season = '2023-24', season_type_all_star = 'Regular Season', per_mode_detailed = 'PerGame', measure_type_detailed_defense = 'Advanced', rank = 'N')

# Convert to a DataFrame
adv_stats_df = adv_stats.get_data_frames()[0]

# Display the structure
adv_stats_df.info()

# Keep desired columns (variables)
adv_stats_df = adv_stats_df[['PLAYER_NAME', 'TEAM_ABBREVIATION', 'GP', 'AST_PCT', 'PACE']]

# rename column
adv_stats_df.rename(columns = {'GP' : 'G'}, inplace = True)

# View the dataset
adv_stats_df.head()

"""### Scoring Stats"""

# Get scoring stats from 2023-2024 season
score_stats = LeagueDashPlayerStats(season = '2023-24', season_type_all_star = 'Regular Season', per_mode_detailed = 'PerGame', measure_type_detailed_defense = 'Scoring', rank = 'N')

# Convert to a DataFrame
score_stats_df = score_stats.get_data_frames()[0]

# Display the structure
score_stats_df.info()

# Keep desired columns (variables)
score_stats_df = score_stats_df[['PLAYER_NAME', 'TEAM_ABBREVIATION', 'GP', 'PCT_PTS_2PT', 'PCT_PTS_3PT','PCT_PTS_PAINT']]

# rename column
score_stats_df.rename(columns = {'GP' : 'G'}, inplace = True)

# View the dataset
score_stats_df.head()

"""## Merge API Data"""

# Merging the DataFrames together
## List the datasets to merge
dfs = [hustle_stats_df,
       passing_stats_df,
       reb_stats_df,
       post_stats_df,
       iso_stats_df,
       pnr_ball_df,
       pnr_roll_df,
       spot_up_df,
       cut_stats_df,
       def_stats_df,
       adv_stats_df,
       score_stats_df]

## Merge the datasets
api_df = reduce(lambda left, right: pd.merge(left, right, on=['PLAYER_NAME', 'TEAM_ABBREVIATION', 'G'], how = 'outer'), dfs)

## Rename the player name column
api_df.rename(columns = {'PLAYER_NAME' : 'Player'}, inplace = True)

## Check the first few rows
api_df.head()

api_df.info()

"""Due to the nature of the data we have collected from the api, some players appear multiple times in our dataset. We have to try to aggregate their statistics together so that there is only one row per player."""

def aggregate_player_stats(df):
    # Step 1: Identify players who appear multiple times
    multiple_players = df['Player'].value_counts()
    multiple_players = multiple_players[multiple_players > 1].index

    new_rows = []

    for player in multiple_players:
        player_df = df[df['Player'] == player]

        # Get the unique teams for the player
        unique_teams = player_df['TEAM_ABBREVIATION'].unique()

        # Calculate the total games played across all teams
        total_games = player_df['G'].max()

        # Step 2: Calculate the weighted average for each statistic
        weighted_stats = {}

        for column in player_df.columns:
            if column in ['Player', 'TEAM_ABBREVIATION']:
                continue

            if player_df[column].notna().sum() == 0:
                weighted_stats[column] = np.nan
            elif player_df[column].notna().sum() == 1:
                weighted_stats[column] = player_df[column].dropna().values[0]
            else:
                weighted_stats[column] = np.average(player_df[column].dropna(), weights=player_df['G'][player_df[column].notna()])

        # Determine the team abbreviation for the new row
        if len(unique_teams) == 1:
            team_abbreviation = unique_teams[0]  # Keep the same team abbreviation if only one team
        else:
            team_abbreviation = 'TOT'  # Use 'TOT' if the player has multiple teams

        # Step 3: Create a new row with the determined team abbreviation
        new_row = {'Player': player, 'TEAM_ABBREVIATION': team_abbreviation, 'G': total_games}
        new_row.update(weighted_stats)
        new_rows.append(new_row)

        # Remove the old rows for this player
        df = df[df['Player'] != player]

    # Step 4: Append the new rows
    new_rows_df = pd.DataFrame(new_rows)
    df = pd.concat([df, new_rows_df], ignore_index=True)

    return df

# Use the function on the nba_api dataframe
api_new = aggregate_player_stats(api_df)

# check the new data
api_new.head()

"""Now we can check if the new dataset has multiple instances of the same player."""

# find the number of times a player shows up in the dataset
player_counts = api_new['Player'].value_counts()

# see if any players appear more than once
len(player_counts[player_counts > 1])

"""There are many instances of NaN in the dataset. I will replace those instances with 0 to make it easy. However, there are other ways of dealing with this issue. I am using 0 because I am assuming the player does not have enough of that stat or did not qualify for it to be recorded, meaning that statistic is not relevant to the player's abilities or tendencies."""

# replace NaN values with 0
api_new = api_new.fillna(0)

# check structure of data
api_new.info()

"""# Final Dataset
The final dataset will be the combination of the web-scraped data and the data from the nba_api. This will have a collection of stats on players from the 2023-2024 NBA season. To get the final dataset, we have to merge the two dataframes we have collected so far.
"""

# drop unwanted variables before merging
api_new.drop(['G', 'TEAM_ABBREVIATION'], axis = 1, inplace = True)

# merge the two dataframes to create the overall dataset
NBA24 = pd.merge(web_df, api_new, on = 'Player', how = 'left')
NBA24.head(10)

# check the structure of the data
NBA24.info()

"""Before exporting this dataset to a file, there are some things which must be fixed and changed. First, all of the columns should be the correct type.

## Changing Data Types
"""

NBA24.iloc[:, :79].dtypes

"""The columns from the api_new dataframe are all the correct data types, however, the columns from the web_df dataframe are all objects. We need to change many of these columns to numeric data types. The first 78 columns in the NBA24 dataset are from the web_df dataframe."""

# Define the start and end indices (inclusive)
start_idx = 4
end_idx = 79

# Loop through the specified column range and convert each to float
for col_idx in range(start_idx, end_idx + 1):
    col_name = NBA24.columns[col_idx]
    NBA24[col_name] = pd.to_numeric(NBA24[col_name], errors='coerce')

# convert Age to float
NBA24 = NBA24[NBA24['Age'] != 'Age']
NBA24['Age'] = NBA24['Age'].astype(float)

NBA24.iloc[:, :79].dtypes

"""## Transforming Columns
In the code below, I will ensure that all the statistics are on the per-game basis and not the season totals.
"""

cols_to_trans = ['OWS', 'DWS', 'WS', 'BadPass', 'LostBall', 'SFC', 'OFC', 'SFD', 'OFD', 'PGA', 'And1', 'Blkd', '#D']
for col in cols_to_trans:
    NBA24[col] = np.where(NBA24['G'] != 0, NBA24[col] / NBA24['G'], np.nan)

NBA24.head()

NBA24.info()

"""## Export Data to .csv"""

file_name = 'NBA24.csv'

NBA24.to_csv(file_name, index = False)

# the file should show up in the current working directory