# -*- coding: utf-8 -*-
"""Player Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fk3-cuQ3ijwwoLgmfdhuFmtF0cKmaYsz

# Player Clustering
In this file, I will cluster together from the NBA24 dataset I gathered previously. I will use PCA and k-means clustering to achieve this. Let's take a look at the dataset once again before beginning.
"""

import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import warnings

# read in the .csv file
NBA24 = pd.read_csv('/content/NBA24.csv')

# take a look at the dataset
NBA24.head()

# drop duplicate columns
# Find columns that contain '_y'
columns_with_y = [col for col in NBA24.columns if '_y' in col]

# Drop these columns
NBA24 = NBA24.drop(columns=columns_with_y)

# look at structure of the dataset
NBA24.info()

"""## PCA

Because there are 144 columns, we need to use PCA to reduce the dimensionality before clustering.
"""

# Drop unwanted columns
NBA24_subset = NBA24.drop(['Player', 'Pos', 'Age', 'Tm', 'GS'], axis = 1)

# Filter subset to include players with at least 30 games played and 12 minutes per game
NBA24_subset = NBA24_subset[(NBA24_subset['G'] >= 30) & (NBA24_subset['MP'] >= 12)]

# Drop 'G' and 'MP' columns
NBA24_subset.drop(['G', 'MP'], axis = 1, inplace = True)

# Identify numerical columns
numerical_features = NBA24_subset.select_dtypes(include=['float64', 'int64']).columns

# Standardizing only the numerical features
scaler = StandardScaler()
NBA_scaled = scaler.fit_transform(NBA24_subset[numerical_features])

# Convert scaled data back to a DataFrame
NBA_scaled = pd.DataFrame(NBA_scaled, columns=numerical_features)

# Replace NaNs with 0
NBA_scaled = NBA_scaled.fillna(0)

# Initialize PCA without specifying the number of components
pca = PCA()

# Fit PCA on the scaled data
pca.fit(NBA_scaled)

# Plot the cumulative explained variance ratio
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
plt.plot(range(1, len(pca.explained_variance_ratio_) + 1), pca.explained_variance_ratio_.cumsum(), marker='o', linestyle='--')
plt.xlabel('Number of Principal Components')
plt.ylabel('Cumulative Explained Variance')
plt.title('Explained Variance vs. Number of Components')
plt.grid(True)
plt.show()

"""## Feature Selection"""

# ignore warnings
warnings.filterwarnings('ignore')

# Define range of principal components and clusters to test
component_range = range(16, 28)  # Testing 18 to 25 components
cluster_range = range(8, 12)    # Testing 8 to 12 clusters

# Storage for evaluation results
results = []

for n_components in component_range:
    # Apply PCA with the current number of components
    pca = PCA(n_components=n_components)
    data_pca = pca.fit_transform(NBA_scaled)

    for n_clusters in cluster_range:
        # Apply K-means clustering
        kmeans = KMeans(n_clusters=n_clusters, random_state=23)
        clusters = kmeans.fit_predict(data_pca)

        # Evaluate clustering performance
        inertia = kmeans.inertia_
        silhouette_avg = silhouette_score(data_pca, clusters)

        # Store results
        results.append({
            'n_components': n_components,
            'n_clusters': n_clusters,
            'silhouette_score': silhouette_avg,
            'inertia': inertia
        })

# Convert results to DataFrame for easier analysis
results_df = pd.DataFrame(results)

# Plot Inertia vs. Number of Principal Components
plt.figure(figsize=(12, 6))
for n_clusters in cluster_range:
    subset = results_df[results_df['n_clusters'] == n_clusters]
    plt.plot(subset['n_components'], subset['inertia'], marker='o', linestyle='--', label=f'{n_clusters} clusters')
plt.xlabel('Number of Principal Components')
plt.ylabel('Inertia')
plt.title('Inertia vs. Number of Principal Components')
plt.legend(title='Number of Clusters')
plt.grid(True)
plt.show()

# Plot Silhouette Score vs. Number of Principal Components
plt.figure(figsize=(12, 6))
for n_clusters in cluster_range:
    subset = results_df[results_df['n_clusters'] == n_clusters]
    plt.plot(subset['n_components'], subset['silhouette_score'], marker='o', linestyle='--', label=f'{n_clusters} clusters')
plt.xlabel('Number of Principal Components')
plt.ylabel('Silhouette Score')
plt.title('Silhouette Score vs. Number of Principal Components')
plt.legend(title='Number of Clusters')
plt.grid(True)
plt.show()

"""Low inertia and a high silhoutte score is desired. From the graphs above, I will use 9 clusters and 16 principal components for the k-means clustering.

## K-means Clustering
"""

# Apply PCA with 16 components
pca = PCA(n_components=16)
data_pca = pca.fit_transform(NBA_scaled)

# Run K-means clustering with 9 clusters
kmeans = KMeans(n_clusters=9, random_state=23)
clusters = kmeans.fit_predict(data_pca)

# Add the cluster numbers to the PCA data
pca_df = pd.DataFrame(data=data_pca, columns=[f'PC{i+1}' for i in range(16)])
pca_df['Cluster'] = clusters

# Filter the NBA24 dataframe to match the NBA24_subset dataframe
NBA24_player = NBA24[(NBA24['G'] >= 30) & (NBA24['MP'] >= 12)]

# Reset index to ensure alignment
pca_df.reset_index(drop=True, inplace=True)
NBA24_player.reset_index(drop=True, inplace=True)

# Add 'Player' column to NBA24_clust dataframe
NBA24_clust = pd.concat([pca_df, NBA24_player[['Player']]], axis=1)

# Add 'Player' column to NBA24_Player dataframe
NBA24_player = pd.concat([NBA24_player, pca_df['Cluster']], axis=1)

# check first rows of new dataset
NBA24_clust.head()

NBA24_clust.info()

"""## Evaluate Clusters

Now that the players have been clustered, we can evaluate the clusters. This includes looking at each of the clusters individually to see the players in each cluster and determining which statistics are most prominent in each cluster.

### Example: Analyzing Cluster 1
"""

# Example: Analyzing cluster 1

# Filter players from cluster 1 only
c1_players = NBA24_clust[NBA24_clust['Cluster'] == 1]

# Look at cluster 1
c1_players

"""After taking a look at the first cluster, it appears the players are primarily 3&D players. If I had to guess, I would say these players spend a lot of time spotting-up and are fairly efficient at catch and shoot attempts.

### Finding Relevant Statistics within each Cluster

To better understand the clusters, we can see which principal components are most prominent in each cluster. This will allow us to understand what statistics the clusters are primarily based on.
"""

# Calculate mean of principal components for each cluster
cluster_means = pca_df.groupby('Cluster').mean()

cluster_means

"""The components with the most relevance to each cluster will be the components with the largest absolute value."""

# Extract loadings (components)
pca_loadings = pd.DataFrame(pca.components_, columns=numerical_features)

# Initialize a dictionary to store feature relevance per cluster
cluster_feature_relevance = {}

# Iterate over each cluster to calculate feature relevance
for cluster in range(kmeans.n_clusters):
    # Filter the data for the current cluster
    cluster_data = pca_df[pca_df['Cluster'] == cluster]

    # Calculate mean principal component values for this cluster
    cluster_mean_pcs = cluster_data.iloc[:, :-1].mean(axis=0)

    # Calculate the contribution of each feature to the cluster's principal components
    cluster_relevance = (pca_loadings.T * cluster_mean_pcs.values).abs().mean(axis=1)

    # Store the results in the dictionary
    cluster_feature_relevance[cluster] = cluster_relevance.sort_values(ascending=False)

# Convert dictionary to DataFrame for easier analysis
cluster_feature_relevance_df = pd.DataFrame(cluster_feature_relevance)
cluster_feature_relevance_df

# Sort the features by their relevance for cluster 1
relevant_features_1 = cluster_feature_relevance_df[1].sort_values(ascending=False).head(10)

# Find average value for each relevant feature from original dataset
c1_data = NBA24_player[NBA24_player['Cluster'] == 1]
features_avg_1 = c1_data[relevant_features_1.index].mean()

# Combine and display the columns
c1_info = pd.concat([relevant_features_1, features_avg_1], axis = 1)
c1_info.columns = ['Contribution', 'Average']

c1_info

"""The code above shows how we can see the most relevant features from a specific cluster. When looking at cluster 1 again, we can see the top 10 most prominent statistics. These include %2P, %3P, 3PAr, PCT_PTS_3PT, and more. We can also see the average for each statistic from cluster 1. For example, players from cluster 1 only take about 35% of shots from 2 point range and 65 percent of shots from 3 point range, on average.

From this output, it is clear that this cluster are primarily role players who are outside scoring threats and provide floor spacing to their teams. The averages from WS, BPM, and DWS show that they may not be the most impactful players.
"""

NBA24_player.groupby('Cluster')['%3-10'].mean().sort_values(ascending=False)

"""We can also compare the average values of the important characteristics to other clusters. Above, we can see that cluster 1 is last in terms of average percent of shots taken between 3 and 10 feet. This confirms what we have already discussed, showing that these players prefer to stay outside the 3 point line."""

NBA24_player[NBA24_player['Cluster'] == 1].sort_values(by = 'PTS', ascending = False).head()

"""Some notable players from cluster 1 include Klay Thompson, Donte DiVincenzo, Trey Murphy III, Norman Powell, and Grayson Allen.

## Description of each Cluster

This section will repeat the previous code chunks to find the relevant statistics/features of each cluster. Then, I will put a summary of each cluster at the end of the section.

### Cluster 0
"""

# Sort the features by their relevance for cluster 0
relevant_features_0 = cluster_feature_relevance_df[0].sort_values(ascending=False).head(10)

# Find average value for each relevant feature from original dataset
c0_data = NBA24_player[NBA24_player['Cluster'] == 0]
features_avg_0 = c0_data[relevant_features_0.index].mean()

# Combine and display the columns
c0_info = pd.concat([relevant_features_0, features_avg_0], axis = 1)
c0_info.columns = ['Contribution', 'Average']

c0_info

NBA24_player[NBA24_player['Cluster'] == 0].sort_values(by = 'PTS', ascending = False).head()

"""### Cluster 2"""

# Sort the features by their relevance for cluster 2
relevant_features_2 = cluster_feature_relevance_df[2].sort_values(ascending=False).head(10)

# Find average value for each relevant feature from original dataset
c2_data = NBA24_player[NBA24_player['Cluster'] == 2]
features_avg_2 = c2_data[relevant_features_2.index].mean()

# Combine and display the columns
c2_info = pd.concat([relevant_features_2, features_avg_2], axis = 1)
c2_info.columns = ['Contribution', 'Average']

c2_info

NBA24_player[NBA24_player['Cluster'] == 2].sort_values(by = 'PTS', ascending = False).head()

"""### Cluster 3"""

# Sort the features by their relevance for cluster 3
relevant_features_3 = cluster_feature_relevance_df[3].sort_values(ascending=False).head(10)

# Find average value for each relevant feature from original dataset
c3_data = NBA24_player[NBA24_player['Cluster'] == 3]
features_avg_3 = c3_data[relevant_features_3.index].mean()

# Combine and display the columns
c3_info = pd.concat([relevant_features_3, features_avg_3], axis = 1)
c3_info.columns = ['Contribution', 'Average']

c3_info

NBA24_player[NBA24_player['Cluster'] == 3].sort_values(by = 'PTS', ascending = False).head()

"""### Cluster 4"""

# Sort the features by their relevance for cluster 4
relevant_features_4 = cluster_feature_relevance_df[4].sort_values(ascending=False).head(10)

# Find average value for each relevant feature from original dataset
c4_data = NBA24_player[NBA24_player['Cluster'] == 4]
features_avg_4 = c4_data[relevant_features_4.index].mean()

# Combine and display the columns
c4_info = pd.concat([relevant_features_4, features_avg_4], axis = 1)
c4_info.columns = ['Contribution', 'Average']

c4_info

NBA24_player[NBA24_player['Cluster'] == 4].sort_values(by = 'PTS', ascending = False).head()

"""### Cluster 5"""

# Sort the features by their relevance for cluster 5
relevant_features_5 = cluster_feature_relevance_df[5].sort_values(ascending=False).head(10)

# Find average value for each relevant feature from original dataset
c5_data = NBA24_player[NBA24_player['Cluster'] == 5]
features_avg_5 = c5_data[relevant_features_5.index].mean()

# Combine and display the columns
c5_info = pd.concat([relevant_features_5, features_avg_5], axis = 1)
c5_info.columns = ['Contribution', 'Average']

c5_info

NBA24_player[NBA24_player['Cluster'] == 5].sort_values(by = 'PTS', ascending = False).head()

"""### Cluster 6"""

# Sort the features by their relevance for cluster 6
relevant_features_6 = cluster_feature_relevance_df[6].sort_values(ascending=False).head(10)

# Find average value for each relevant feature from original dataset
c6_data = NBA24_player[NBA24_player['Cluster'] == 6]
features_avg_6 = c6_data[relevant_features_6.index].mean()

# Combine and display the columns
c6_info = pd.concat([relevant_features_6, features_avg_6], axis = 1)
c6_info.columns = ['Contribution', 'Average']

c6_info

NBA24_player[NBA24_player['Cluster'] == 6].sort_values(by = 'PTS', ascending = False).head()

"""### Cluster 7"""

# Sort the features by their relevance for cluster 7
relevant_features_7 = cluster_feature_relevance_df[7].sort_values(ascending=False).head(10)

# Find average value for each relevant feature from original dataset
c7_data = NBA24_player[NBA24_player['Cluster'] == 7]
features_avg_7 = c7_data[relevant_features_7.index].mean()

# Combine and display the columns
c7_info = pd.concat([relevant_features_7, features_avg_7], axis = 1)
c7_info.columns = ['Contribution', 'Average']

c7_info

NBA24_player[NBA24_player['Cluster'] == 7].sort_values(by = 'PTS', ascending = False).head()

"""### Cluster 8"""

# Sort the features by their relevance for cluster 8
relevant_features_8 = cluster_feature_relevance_df[8].sort_values(ascending=False).head(10)

# Find average value for each relevant feature from original dataset
c8_data = NBA24_player[NBA24_player['Cluster'] == 8]
features_avg_8 = c8_data[relevant_features_8.index].mean()

# Combine and display the columns
c8_info = pd.concat([relevant_features_8, features_avg_8], axis = 1)
c8_info.columns = ['Contribution', 'Average']

c8_info

NBA24_player[NBA24_player['Cluster'] == 8].sort_values(by = 'PTS', ascending = False).head()

"""### Overall Summary

The clusters provide information on players playstyles, abilities, and tendencies. The 9 clusters help to understand the types of players that make up NBA rosters. Below are summaries of each cluster. The indexing of the clusters starts at 0, so the clusters are numbered 0-8 instead of 1-9.

Cluster 0:


*   The most prominent stats are field goal attempts, points, usage percentage, assists, and points generated by assists. Some notable players are Luka Doncic, Shai GIlgeous-Alexander, Jalen Brunson, Devin Booker, and Kevin Durant. This cluster seems to represent superstar players who are typically the offensive hubs of their team. These players will often be the primary scorers and playmakers in the offense.


Cluster 1:


*   The prominent features include %2P, %3P, 3PAr, PCT_PTS_3PT, and more. This cluster contains primarily role players who are outside scoring threats and provide floor spacing to their teams. Some notable players from cluster 1 include Klay Thompson, Donte DiVincenzo, Trey Murphy III, Norman Powell, and Grayson Allen. The averages from WS, BPM, and DWS show that they may not be the most impactful players outside of shooting. However, the threat they provide from distance helps their team's offense and spaces the floor for others.

Cluster 2:


*  The most prominent stats are field goal attempts, usage percentage, 3 point attempts, assist percentage, and points. Most of these stats are low on average, showing that these players are not very involved in the offense and aren’t relied on heavily. Some notable players include Marvin Bagley III, Moritz Wagner, Onyeka Okongwu, Jalen Smith, and Amen Thompson. This cluster seems to represent hustle players and glue-guys, making their impact through characteristics such as rebounding, screening, cutting, or defense.


Cluster 3:


*   The most prominent features of this cluster are 3 pointers made and 3 point attempts, assist percentage, points created, and possessions as the pick and roll ball handler. Some notable players include Desmond Bane, Cade Cunningham, Anfernee Simons, Cam Thomas, and Dejounte Murray. This cluster represents ball-handling guards who have the ability to run the pick-and-roll, either as a passer or a shooter coming off the screen. Consequently, these players can be combo-guards and play the 1 or the 2.


Cluster 4:


*   Free throws, shooting fouls drawn, offensive rebound percentage, and 2 pointers are prominent features for cluster 4. These features seem to indicate that this cluster represents inside bigs who are great rebounders and rim-runners. Some notable players are Deandre Ayton, Jarrett Allen, Rudy Gobert, Jalen Duren, and Nic Claxton. These players also possess rim-protection ability.

Cluster 5:


*   The prominent features for cluster 5 are steals, true shooting percentage, effective field goal percentage, and deflections. Some notable players are Bogdan Bogdanovic, Michael Porter Jr., Keldon Johnson, De’Andre Hunter, and Kelly Oubre Jr. This cluster seems to contain volatile scoring wings. These players’ efficiency and defensive impact is not very good when compared to other clusters, but they do get deflections and can heat up offensively at any given moment.


Cluster 6:


*   Cluster 6’s prominent features are distance of shots, % of shots that are 3’s, % of shots that are 2’s, BPM, and VORP. Some notable players include Alec Burks, Lonnie Walker IV, Malaki Branham, Gradey Dick, and Marcus Sasser. From the features and notable players, this cluster seems to represent primarily backup guards who will provide an offensive punch. Their scoring is fairly balanced from both 2-point and 3-point distance, but they don’t provide much else statistically speaking. These players also are replaceable role players and do not have too big of an impact on their team.

Cluster 7:


*   The prominent features include offensive rating, win shares, rebounding, % shots that are 3 pointers, and BPM. Some notable players include Julius Randle, Lauri Markannen, Jaren Jackson Jr., Karl-Anthony Towns, and Pascal Siakam. From the features and the players, it seems that this cluster represents above-average to star-level frontcourt players. Their size enables them to be good rebounders inside, but they offer versatile scoring and have the ability to score from the outside to go with their size.


Cluster 8:


*   The prominent features are PER, post touches, field goal percentage, possessions as the roll man in pick and rolls, and rebounding. Some notable players include Joel Embiid, Giannis Antetokounmpo, Anthony Davis, Victor Wembanyama, and Alperen Sengun. This cluster represents hyper-efficient superstar bigs who dominate in the post and prefer to play inside. Along with their inside scoring presence, they are great rebounders and great at being the roller in the pick and roll.
"""